import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";

const open_Sans = Open_Sans({
  weight:"400",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${open_Sans.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar/>
        
        {children}
        
        </body>
    </html>
  );
}
